# Generated by Django 6.0.4 on 2026-05-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=2)),
                ('className', models.IntegerField(max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
